# Dockerfile para o Frontend
FROM node:20-alpine
WORKDIR /app
COPY ./frontend ./frontend
WORKDIR /app/frontend
RUN npm install -g live-server
EXPOSE 8080
CMD ["live-server", ".", "--port=8080", "--host=0.0.0.0"]