version: '3.8'
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/app/frontend
    restart: unless-stopped
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app/backend
    restart: unless-stopped
