# Dockerfile para o Backend
FROM node:20-alpine
WORKDIR /app
COPY ./backend ./backend
WORKDIR /app/backend
# Adicione aqui comandos para instalar dependências do backend se necessário
EXPOSE 3000
CMD ["node", "src/server.js"]